name: unix-domain-client
version: '0.1'
summary: Simple Unix domain client example written in Go.
description: |
  Simple Unix domain client example written in Go.  The
  primary usage is to test sharing a socket between snaps
  from the same developer/publisher via the content interface.

grade: devel
confinement: strict

plugs:
   content:
     content: socket-directory
     target: $SNAP_DATA/sockets

apps:
  unix-domain-client:
    command: bin/client-wrapper
    plugs: [network]

parts:
  unix-domain-client-common:
    plugin: dump
    source: .
    filesets:
      bin: [bin/client-wrapper]
    stage: [$bin]
    prime: [$bin]

  unix-domain-client:
    source: .
    plugin: go
    go-importpath: github.com/tonyespy/unix-domain-client
